network/urls.py
from django.urls import path

from . import views

app_name = "network"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<int:profile_id>", views.user_profile, name="user_profile"),
    path("add_followers/<int:profile_id>", views.add_followers, name="add_followers"),
    path("remove_followers/<int:profile_id>", views.remove_followers, name="remove_followers"),
    path("posts_following", views.posts_following, name="posts_following"),

    path("edit/<int:post_id>", views.edit, name="edit"),
    path("like/<int:post_id>", views.like, name="like"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver

class User(AbstractUser):
    id = models.AutoField(primary_key=True)
    profile_picture = models.ImageField(null=True, blank=True, upload_to="images/profile/")

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

class Post(models.Model):
    post_creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="creator", null=True)
    body = models.TextField(blank=False, null=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="post_likes", blank=True)
    dislikes = models.ManyToManyField(User, related_name="post_dislikes", blank=True)


    def __str__(self):
        return f"{self.post_creator}: {self.body}"

    def total_likes(self):
        return self.likes.count()


class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE, related_name="user", blank=True)
    followers = models.ManyToManyField(User, related_name="followers", blank=True)
    following = models.ManyToManyField(User, related_name="following", blank=True)

    def __str__(self):
        return f"{self.user}: {self.user.id}"

class Liked(models.Model):
    user_liked = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_liked", null=True, blank=True)
    post_liked = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post_liked", null=True, blank=True)
    is_liked = models.BooleanField(default=False)

network/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('body',)

        labels = {
            'body':'',
        }

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'autocomplete': 'off', 'rows':2, 'id':'post-form',}),
        }

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
import json
from django.core.serializers import serialize

from .models import User, Post, UserProfile, Liked
from .forms import PostForm


def index(request):
    posts = Post.objects.all()
    posts = posts.order_by("-timestamp").all()
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid:
            post_form = form.save(commit=False)
            post_form.post_creator = request.user
            post_form.save()
        return HttpResponseRedirect(reverse ('network:index'))
    else:
        form = PostForm()

    return render(request, "network/index.html", {
        "form": form,
        "posts": posts,
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")
    

def user_profile(request, profile_id):
    profile = UserProfile.objects.get(pk=profile_id)
    profile_user = profile.user

    signed_user = UserProfile.objects.get(pk=request.user.id)
    signed_user_profile = signed_user.user
    signed_user_following = signed_user.following.all()

    posts = Post.objects.filter(post_creator = profile_user)
    posts = posts.order_by("-timestamp").all()
    followers = profile.followers.all()
    follwing = profile.following.all()
    
    user_followers_id = []
    for follower in followers:
        user_followers_id.append(follower.id)

    return render(request, "network/user_profile.html", {
        "profile": profile,
        "profile_user": profile_user,
        "posts": posts,
        "followers": followers,
        "following": follwing,
        "user_followers_id": user_followers_id,
        "signed_user_following": signed_user_following,
    })

def edit(request, post_id):
    post = Post.objects.get(pk = post_id)
    posts = list(Post.objects.all().values())
    if request.method == "GET":
        return HttpResponse(post)
    
    elif request.method == "PUT":
        POST = json.loads(request.body)
        post.body = POST['postBody']
        post.save()

        data = {
            'postBody': post.body,
        }
        return JsonResponse(data)
    
def like(request, post_id):
    user_like = request.user

    if request.method == "PUT":
        data = json.loads(request.body)
        post_id = data['id']
        post = Post.objects.get(id = post_id)
        post.save()

        if user_like not in post.likes.all():
            post.likes.add(user_like)
            post.save()
        else:
            post.likes.remove(user_like)
            post.save()

        post_likes = serialize('json', post.likes.all())

        data = {
            'post_likes': post_likes,
            'likes': post.likes.all().count(),
        }

        return JsonResponse(data)
    

# Add followers
def add_followers(request, profile_id):
    if request.user.is_authenticated:
        if request.method == "POST":
            me = UserProfile.objects.get(pk=request.user.id)
            profile = UserProfile.objects.get(pk=profile_id)
            profile.followers.add(request.user)
            me.following.add(profile.user)
            return HttpResponseRedirect(reverse ('network:user_profile', args=(str(profile_id))))
        
# Remove followers
def remove_followers(request, profile_id):
    if request.user.is_authenticated:
        if request.method == "POST":
            me = UserProfile.objects.get(pk=request.user.id)
            profile = UserProfile.objects.get(pk=profile_id)
            profile.followers.remove(request.user)
            me.following.remove(profile.user)
            return HttpResponseRedirect (reverse ('network:user_profile', args=(str(profile_id))))
        

def posts_following(request):
    me = UserProfile.objects.get(pk=request.user.id)
    me_following = me.following.all()
    posts = []
    followers_id = []
    for follower in me_following:
        followers_id.append(follower.id)
    all_posts = Post.objects.order_by("-timestamp").all()
    for post in all_posts:
        if post.post_creator.id in followers_id:
            posts.append(post)
    
    return render(request, "network/posts_following.html", {
        "me": me,
        "posts": posts,
    })

network/templates/network/index.html
{% extends "network/layout.html" %}

{% load static %}


{% block body %}
    {% block script %}
    <script src="{% static 'network/index.js' %}"></script>
    <script src="{% static 'network/like.js' %}"></script>
    {% endblock %}
    <div class="col d-flex justify-content-center mt-5 mb-5" id="all_posts">
        <div class="col-lg-9">
            <h3>All Posts</h3><br>
        
            {% if user.is_authenticated %}
            <div id="new_post" class="border px-5 py-4">
                <h5 class="mb-4">New Post</h5>
                <form action="", method="POST" enctype="">
                    {% csrf_token %}
                    {{ form }}
                    <input id="post_button" type="submit" value="Post" class="btn mt-4" style="background-color: #00C5CD; color: white;">
                </form>
            </div>
            {% endif %}
        
            <div id="all-posts" class="card posts px-5 pt-4 pb-4">
            {% for post in posts %}
                <div class="posts-div">
        
                    {% if user.is_authenticated %}
                    <div>
                        <h6><a href="{% url 'network:user_profile' post.post_creator.id %}" style="text-decoration: none; color: #00C5CD;">{{ post.post_creator }}</a></h6>
                    </div>
                    {% else %}
                    <div>
                        <h6 style="text-decoration: none; color: #00C5CD;">{{ post.post_creator }}</h6>
                    </div>
                    {% endif %}
        
                    <div class="input-div"></div>
        
                    <input type="hidden" id="post-id" name="post-id" value="{{ post.id }}">
                    <div class="post-body mb-2">{{ post.body }}</div>
                    <div style="font-size:14px" class="text-muted mb-2">{{ post.timestamp }}</div>
        
                    <!-- Like Post -->
                    {% if user.is_authenticated %}
                    <input id="request-user" type="hidden" value="{{ request.user }}">
                    <button type="submit" class="like-button" data-liked="{{ post.id }}" id="post-like{{ post.id }}" name="" value="{{ post.id }}" style="border:0; background-color: transparent;">
                        {% if request.user in post.likes.all %}
                        <i style="color: red;" class="fa-solid fa-heart"></i><span class="ps-2" id="likes-number">{{ post.total_likes }}</span>
        
                        {% else %}
                        <i style="color: grey;" class="fa-solid fa-heart"></i><span class="ps-2" id="likes-number">{{ post.total_likes }}</span>
        
                        {% endif %}
        
                    </button>
                    {% endif %}
                    <br>
        
                    <!-- Edit Post -->
                    {% if request.user == post.post_creator %}
                    <button style="background-color: #00C5CD; color: white;" class="btn btn-sm mt-2" data-post = "{{ post.id }}">Edit</button>
                    {% endif %}
                    <hr class="mb-4">
        
        
                </div>
                {% empty %}
                    No Posts...
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        <script src="https://kit.fontawesome.com/b1a21454b8.js" crossorigin="anonymous"></script>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light px-5">
            <a class="navbar-brand" href="#">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:user_profile' request.user.id %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:posts_following' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% load static %}

{% block body %}

    <div class="d-flex justify-content-center mt-3">
        <div class="col-lg-6 mt-5">
            <h2>Login</h2>

            {% if message %}
                <div>{{ message }}</div>
            {% endif %}

            <div class="light-grey-box py-5 px-4">
                <form action="{% url 'network:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group mb-3">
                        <input class="form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <input class="btn btn-primary mb-3" type="submit" value="Login">
                </form>

                Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>
            </div>
        </div>
    </div>
{% endblock %}

network/templates/network/posts_following.html
{% extends "network/layout.html" %}
{% load static %}


{% block body %}

{% block script %}
    <script src="{% static 'network/like.js' %}"></script>
{% endblock %}

<div class="col d-flex justify-content-center mt-5 mb-5" id="all_posts">
    <div class="col-lg-9">
        <h5>Posts</h5>
        <div id="all-posts" class="card posts px-5 pt-4 pb-4">
            {% for post in posts %}
            <div class="posts-div">
                {% if user.is_authenticated %}
                    <div>
                        <h6><a href="{% url 'network:user_profile' post.post_creator.id %}" style="text-decoration: none; color: #00C5CD;">{{ post.post_creator }}</a></h6>
                    </div>
                    {% else %}
                    <div>
                        <h6 style="text-decoration: none; color: #00C5CD;">{{ post.post_creator }}</h6>
                    </div>
                {% endif %}

                <div class="input-div"></div>

                <input type="hidden" id="post-id" name="post-id" value="{{ post.id }}">
                <div class="post-body mb-2">{{ post.body }}</div>
                <div style="font-size:14px" class="text-muted mb-2">{{ post.timestamp }}</div>

                <!-- Like Post -->
                {% if user.is_authenticated %}
                {% csrf_token %}
                <input id="request-user" type="hidden" value="{{ request.user }}">
                <button type="submit" class="like-button" data-liked="{{ post.id }}" id="post-like{{ post.id }}" name="" value="{{ post.id }}" style="border:0; background-color: transparent;">
                    {% if request.user in post.likes.all %}
                    <i style="color: red;" class="fa-solid fa-heart"></i><span class="ps-2" id="likes-number">{{ post.total_likes }}</span>
    
                    {% else %}
                    <i style="color: grey;" class="fa-solid fa-heart"></i><span class="ps-2" id="likes-number">{{ post.total_likes }}</span>
    
                    {% endif %}
    
                </button>
                {% endif %}
                
                <hr class="mb-4">

            </div>
            {% empty %}
                No Posts...
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% load static %}

{% block body %}

    <div class="d-flex justify-content-center mt-3">
        <div class="col-lg-6 mt-5">
            <h2>Register</h2>

            {% if message %}
                <div>{{ message }}</div>
            {% endif %}
            <div class="light-grey-box py-5 px-4">
                <form action="{% url 'network:register' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group mb-3">
                        <input class="form-control" type="email" name="email" placeholder="Email Address">
                    </div>
                    <div class="form-group mb-3">
                        <input class="form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group mb-3">
                        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
                    </div>
                    <input class="btn btn-primary mb-3" type="submit" value="Register">
                </form>

            Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>
            </div>
        </div>
    </div>
{% endblock %}

network/templates/network/user_profile.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}

{% block script %}
    <script src="{% static 'network/like.js' %}"></script>
    <script src="{% static 'network/edit.js' %}"></script>
{% endblock %}

<div class="col container-fluid d-flex justify-content-center" id="profile-body">
    <div class="col-lg-9 pt-5" id="profile-box">
        <div id="profile-body" class="row">
            <div id="user-picture-info" class="d-flex">
                    
                <div id="user-picture"; class="col-lg-2">
                    {% if user.profile_picture %}
                        <img src="{{ user.profile_picture.url }}" width="150" height="150" style="margin-right:20px;" class="">
                    {% else %}
                        <img src="{% static 'network/images/profile/Profile-Icon.png' %}" width="150" height="150" class="">
                    {% endif %}
                </div>

                <div id="user-info"; class="col-lg-10">
                    <div class="col">
                        <h5 class="ms-3">{{ profile_user }}</h5>
                        <div class="row">
                            <div id="follow-unfollow-buttons"; class="d-flex col-lg-3 mt-1">
                                <!-- Follow button -->
                                <div class="col-lg-6 text-center">
                                <form action="{% url 'network:add_followers' profile_user.id %}" method="POST" class="me-2">
                                    {% csrf_token %}
                                    {% if request.user.id == profile_user.id %}
                                    <button disabled class="btn btn-sm" type="submit button" style="background-color: #009999; color: white;">Follow</button>
                                    {% elif request.user.id in user_followers_id %}
                                    <button disabled class="btn btn-sm" type="submit button" style="background-color: #009999; color: white;">Follow</button>
                                    {% else %}
                                    <button class="btn btn-sm" type="submit button" style="background-color: #009999; color: white;">Follow</button>
                                    {% endif %}
                                </form>
                                </div>
                                <!-- Unfollow button -->
                                <div class="col-lg-6 text-center">
                                <form action="{% url 'network:remove_followers' profile_user.id %}" method="POST">
                                    {% csrf_token %}
                                    {% if request.user.id == profile_user.id %}
                                    <button disabled class="btn btn-sm" type="submit button" style="background-color: #009999; color: white;">Unfollow</button>
                                    {% elif request.user.id not in user_followers_id %}
                                    <button disabled class="btn btn-sm" type="submit button" style="background-color: #009999; color: white;">Unfollow</button>
                                    {% else %}
                                    <button class="btn btn-sm" type="submit button" style="background-color: #009999; color: white;">Unfollow</button>
                                    {% endif %}
                                </form>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="d-flex col-lg-3">
                                <div class="col-lg-6 text-center" style=" font-size: 25px;">{{ followers.count }}</div>
                                <div class="col-lg-6 text-center" style="font-size: 25px;">{{ following.count }}</div>
                            </div>
                        </div>
                        <div class="row">
                        <div class="d-flex col-lg-3">
                            <div class="col-lg-6 text-center" id="followers"><small>Followers</small></div>
                            <div class="col-lg-6 text-center" id="following"><small>Following</small></div>
                        </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        
        <div id="all_posts" class="mt-4 mb-4">
            <h5>{{ profile_user }}'s posts</h5>
            <div id="all-posts" class="card posts px-5 pt-4 pb-4">
                {% for post in posts %}
                <div class="posts-div">
                    {% if user.is_authenticated %}
                    <div>
                        <h6><a href="{% url 'network:user_profile' post.post_creator.id %}" style="text-decoration: none; color: #00C5CD;">{{ post.post_creator }}</a></h6>
                    </div>
                    {% else %}
                    <div>
                        <h6 style="text-decoration: none; color: #00C5CD;">{{ post.post_creator }}</h6>
                    </div>
                    {% endif %}
                    
                    <div class="input-div"></div>

                    <input type="hidden" id="post-id" name="post-id" value="{{ post.id }}">
                    <div class="post-body mb-2">{{ post.body }}</div>
                    <div style="font-size:14px" class="text-muted mb-2">{{ post.timestamp }}</div>

                    <!-- Like Post -->
                    {% if user.is_authenticated %}
                    <input id="request-user" type="hidden" value="{{ request.user }}">
                    <button type="submit" class="like-button" data-liked="{{ post.id }}" id="post-like{{ post.id }}" name="" value="{{ post.id }}" style="border:0; background-color: transparent;">
                        {% if request.user in post.likes.all %}
                        <i style="color: red;" class="fa-solid fa-heart"></i><span class="ps-2" id="likes-number">{{ post.total_likes }}</span>

                        {% else %}
                        <i style="color: grey;" class="fa-solid fa-heart"></i><span class="ps-2" id="likes-number">{{ post.total_likes }}</span>

                        {% endif %}

                    </button>
                    {% endif %}
                    <br>

                    <!-- Edit Post -->
                    {% if request.user == post.post_creator %}
                    <button style="background-color: #00C5CD; color: white;" class="btn btn-sm mt-2" data-post = "{{ post.id }}">Edit</button>
                    {% endif %}
                    <hr class="mb-4">
                </div>
                {% empty %}
                     No Posts...
                {% endfor %}
                    
            </div>
                
        </div>
        
    </div>

</div>

<div class="pop-up-box-followers">
    <div class="overlay-followers"></div>
    <div class="pop-up-body">
        <div class="pop-up-inner-body">
            {% for follower in followers %}
            <div class="d-flex justify-content-between mb-2">
                <div id="user-picture"; class="">
                    {% if user.profile_picture %}
                        <img src="{{ user.profile_picture.url }}" width="50" height="50" style="margin-right:20px;" class="">
                    {% else %}
                        <img src="{% static 'network/images/profile/Profile-Icon.png' %}" width="35" height="35" class="">
                    {% endif %}
                </div>
                <div style="height: 35px; line-height: 35px; text-align: center;" class="ms-3">
                    <a href="{% url 'network:user_profile' follower.id %}" style="text-decoration: none; color: #00C5CD;">{{ follower }}</a>
                </div>
                <div style="height: 35px; display: grid;">   
                        {% if request.user.id == follower.id %}
                        <button class="btn btn-sm ms-3 text-center" style="background-color: white; color: white; margin: auto;">Following</button>
                        {% elif follower in signed_user_following %}
                        <button class="btn btn-sm ms-3 text-center" style="background-color: #009999; color: white; margin: auto; opacity: 0.5;">Following</button>
                        {% else %}
                        <form action="{% url 'network:add_followers' follower.id %}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-sm ms-3 text-center" type="submit button" style="background-color: #009999; color: white; margin: auto;">Follow</button>
                        </form>
                        {% endif %}
                </div>
            </div>
            {% empty %}
                No followers...
            {% endfor %}
        </div>
    </div>
</div>

<div class="pop-up-box-following container-fluid justify-content-center">
    <div class="overlay-following row d-flex"></div>
    <div class="pop-up-body col-lg-3">
        <div class="pop-up-inner-body">
            {% for follower in following %}
            <div class="row">
                <div class="d-flex justify-content-between mb-2">
                    <div id="user-picture"; class="col-lg-2">
                        {% if user.profile_picture %}
                            <img src="{{ user.profile_picture.url }}" width="50" height="50" style="margin-right:20px;" class="">
                        {% else %}
                            <img src="{% static 'network/images/profile/Profile-Icon.png' %}" width="35" height="35" class="">
                        {% endif %}
                    </div>
                    <div style="height: 35px; line-height: 35px;" class="col-lg-6 ms-4">
                        <a href="{% url 'network:user_profile' follower.id %}" style="text-decoration: none; color: #00C5CD;">{{ follower }}</a>
                    </div>
                    <div style="height: 35px;" class="col-lg-4"> 
                            {% if follower in signed_user_following %}
                            <form action="{% url 'network:remove_followers' follower.id %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-sm text-center" type="submit button" style="background-color: #009999; color: white; margin: auto;">Unfollow</button>
                            </form>
                            {% else %}
                            <form action="{% url 'network:add_followers' follower.id %}" method="POST">
                                {% csrf_token %}
                                <button class="btn btn-sm text-center" type="submit button" style="background-color: #009999; color: white; margin: auto;">Follow</button>
                            </form>
                            {% endif %}
                    </div>
                </div>
            </div>
            {% empty %}
                {{ profile_user }} is not following anyone...
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}